[profile.default]
src = "src"
out = "out"
libs = ["lib"]
#evm_version = "Cancun"
optimizer = true

[fmt]
int_types = "short"

[rpc_endpoints]
sonic = "${SONIC_RPC_URL}"
real = "${REAL_RPC_URL}"

[etherscan]
sonic = { key = "${SONICSCAN_API_KEY}", chain = 146, url = "https://api.sonicscan.org/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
